import type { Metadata } from "next";
import "./globals.css";
// import "@/styles/app.css"
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
// import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "next-themes";
import { Providers } from "@/components/providers";
import Loading from "./loading/loading";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "AI Website Builder",
  description: "Generated by create next app",
  icons: {
    icon: "/ai-logo-black.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col dark">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Providers>
              {children}
              {/* <Loading /> */}
            </Providers>
          </ThemeProvider>
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
